dappx/urls.py
# dappx/urls.py

from django.conf.urls import url
from dappx import views

# SET THE NAMESPACE!
app_name = 'dappx'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    #url(r'^register1/$',views.register1,name='register1'),
    #url(r'^signup/$',views.signup,name='signup'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^DanceRegister/$',views.danceRegister,name='danceRegister'),#to be updated 
	url(r'^YogaRegister/$',views.yogaRegister,name='yogaRegister'),
	url(r'^MusicRegister/$',views.musicRegister,name='musicRegister'),
	url(r'^TutorRegister/$',views.TutorRegister,name='TutorRegister'),
	
]

findtution/urls.py
from django.contrib import admin
from django.urls import path , include
from findtution import views
from django.contrib import admin
from django.urls import path , include

app_name = 'findtution'
			

urlpatterns = [
    path('', views.index, name='index'),
    path('index/',  views.index, name='index'),
    path('about/', views.about, name='about'),
    path('blog/', views.blog, name='blog'),
    path('blogs/', views.blogs, name='blogs'),
    path('contact/', views.contact, name='contact'),
    path('courses/', views.courses, name='courses'),
    path('pricing/', views.pricing, name='pricing'),
    path('teacher/', views.teacher, name='teacher'),
    
   
]

website/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls import url, include
from dappx import views

urlpatterns = [
    
    path('', include('findtution.urls')),
    path('admin/', admin.site.urls),
    url(r'reg$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^',include('dappx.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
     
     
]

dappx/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

# dappx/models.py

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class TutorQuestion(models.Model):

    email=models.EmailField(max_length=200, blank=True, null=True)
    user = models.OneToOneField(User,on_delete = models.CASCADE)
    profile_pic = models.ImageField(upload_to = 'profile_pics',blank = True)
    Highest_degree=models.CharField(max_length = 200, blank = True, null = True)
    Upload_certificate=models.ImageField(upload_to = 'Upload_certificate',blank = True)
    state = models.CharField(max_length = 200, blank = True, null = True)
    city = models.CharField(max_length = 200, blank = True, null = True)
    Subjects_you_wish_to_teach = models.CharField(max_length = 200, blank = True, null = True)
    What_is_the_minimum_tenure_you_wish_to_teach_with_us = models.CharField(max_length = 200, blank = True, null = True)
    What_languages_you_speak = models.CharField(max_length=200, blank=True, null = True)
    Give_us_a_short_description_about_yourself = models.TextField(max_length = 500, blank = True, null = True)
    Level_of_targeted_students = models.CharField(max_length = 200, blank = True, null = True)
    #Your_Specialities = models.CharField(max_length = 200, blank = True, null = True)
    Prior_teaching_experience = models.CharField(max_length=200, blank=True, null=True)
    Preferred_time = models.CharField(max_length=200, blank=True, null=True)
    Payment_expectation_per_hour = models.CharField(max_length=200, blank=True, null=True)
    what_are_your_expectations_from_findatution = models.CharField(max_length=300, blank=True, null=True)
    domain = models.CharField(max_length = 200, blank = True, null = True)


class AcademicStudentInfo(models.Model):
    
	email=models.EmailField(max_length=200, blank=True, null=True)
	user = models.OneToOneField(User,on_delete=models.CASCADE)
	profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
	#state = models.CharField(max_length=200, blank=True, null=True)
	city = models.CharField(max_length=200, blank=True, null=True)
	Your_Board = models.CharField(max_length=200, blank=True, null=True)
	Your_class = models.CharField(max_length=200, blank=True, null=True)
	Language_You_Speak = models.CharField(max_length=200, blank=True, null=True)
	Subject_You_want_to_study = models.CharField(max_length=200, blank=True, null=True)
	Preferred_time = models.CharField(max_length=200, blank=True, null=True)
	Stream = models.CharField(max_length=200, blank=True, null=True)

class YogaStudentInfo(models.Model):
    
	email=models.EmailField(max_length=200, blank=True, null=True)
	user = models.OneToOneField(User,on_delete=models.CASCADE)
	profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
	#state = models.CharField(max_length=200, blank=True, null=True)
	city = models.CharField(max_length=200, blank=True, null=True)
	What_Yoga_form_want_to_learn= models.CharField(max_length=200, blank=True, null=True) #we will give choices of all or selected yoga asanas.
	Preferred_time = models.CharField(max_length=200, blank=True, null=True)

class MusicStudentInfo(models.Model):
    
	email=models.EmailField(max_length=200, blank=True, null=True)
	user = models.OneToOneField(User,on_delete=models.CASCADE)
	profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
	#state = models.CharField(max_length=200, blank=True, null=True)
	city = models.CharField(max_length=200, blank=True, null=True)
	What_would_you_like_to_learn = models.CharField(max_length=200, blank=True, null=True) #we will give choices of instrument and classical/western vocals
	Preferred_time = models.CharField(max_length=200, blank=True, null=True)
	
class DanceStudentInfo(models.Model):
    
	email=models.EmailField(max_length=200, blank=True, null=True)
	user = models.OneToOneField(User,on_delete=models.CASCADE)
	profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
	#state = models.CharField(max_length=200, blank=True, null=True)
	city = models.CharField(max_length=200, blank=True, null=True)
	Danceform_You_want_to_learn = models.CharField(max_length=200, blank=True, null=True) #we will give choices of all type of dance forms
	Preferred_time = models.CharField(max_length=200, blank=True, null=True)
	

'''class TutionPointRegister(models.Model):

    email=models.EmailField(max_length=200, blank=True, null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
	#profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    city = models.CharField(max_length=200, blank=True, null=True)
    state = models.CharField(max_length=200, blank=True, null=True)
    Subjects_you_teach = models.CharField(max_length=200, blank=True, null=True)
    What_is_the_minimum_time_you_wish_to_be_with_us = models.CharField(max_length=200, blank=True, null=True)
    What_languages_your_teachers_know = models.CharField(max_length=200, blank=True, null=True)
    Give_us_a_short_description_about_your_institute = models.TextField(max_length=500, blank=True, null=True)
    Level_of_target_students = models.CharField(max_length=200, blank=True, null=True)
    Your_Specialities = models.CharField(max_length=200, blank=True, null=True)
    How_old_is_your_institute = models.CharField(max_length=200, blank=True, null=True)
	#Fee_for_courses = models.CharField(max_length=200, blank=True, null=True)
    what_are_your_expectations_from_findatution = models.CharField(max_length=300, blank=True, null=True)
'''

def __str__(self):
  return self.user.username

dappx/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

# dappx/views.py

from django.shortcuts import render
from dappx.forms import UserForm,TutorQuestionForm,AcademicStudentInfoForm,YogaStudentInfoForm,MusicStudentInfoForm,DanceStudentInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

def index(request):
    return render(request,'dappx/index.html')

#def signup(request):
 #   return render(request,'dappx/register1.html')

@login_required
def special(request):
    return HttpResponse("You are logged in !")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = AcademicStudentInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = AcademicStudentInfoForm()
    return render(request,'dappx/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})


def TutorRegister(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form1 = TutorQuestionForm(data=request.POST)
        if user_form.is_valid() and profile_form1.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form1.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form1.errors)
    else:
        user_form = UserForm()
        profile_form1 = TutorQuestionForm()
    return render(request,'dappx/registration1.html',
                          {'user_form':user_form,
                           'profile_form1':profile_form1,
                           'registered':registered})


def danceRegister(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form3= DanceStudentInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form3.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form3.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form3 = DanceStudentInfoForm()
    return render(request,'dappx/DanceRegister.html',
                          {'user_form':user_form,
                           'profile_form3':profile_form3,
                           'registered':registered})

def yogaRegister(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form4= YogaStudentInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form4.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form4.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form4 = YogaStudentInfoForm()
    return render(request,'dappx/YogaRegister.html',
                          {'user_form':user_form,
                           'profile_form4':profile_form4,
                           'registered':registered})
def musicRegister(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form5= MusicStudentInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form5.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form5.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form5.errors)
    else:
        user_form = UserForm()
        profile_form5 = MusicStudentInfoForm()
    return render(request,'dappx/MusicRegister.html',
                          {'user_form':user_form,
                           'profile_form5':profile_form5,
                           'registered':registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'dappx/login.html', {})

dappx/templates/dappx/DanceRegister.html
{% block head %}
{% load static %}
{% endblock %} {% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
  <title>Registration Form</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet"/>

  <style type="text/css">
html,body{

background: #ECE9E6;  /* fallback for old browsers */
background: -webkit-linear-gradient(to right, #FFFFFF, #ECE9E6);  /* Chrome 10-25, Safari 5.1-6 */
background: linear-gradient(to right, #FFFFFF, #ECE9E6); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
background-image :url({% static 'images/bh4.jpg'%});
}

.button {
        background-color: #4CAF50;
        /* Green */
        border: none;
        color: white;
        padding: 16px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        -webkit-transition-duration: 0.4s;
        /* Safari */
        transition-duration: 0.4s;
        cursor: pointer;
    }

    .button2 {
        background-color: white;
        color: black;
        border: 2px solid #008CBA;
    }

    .button2:hover {
        background-color: #008CBA;
        color: white;
    }

      #graph-card {
  background-color:Transparent;
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
  width: 97%;
  min-height: 100px ;
  margin: 5px;
  transition: 0.3s;
  border-radius: 5px;
  border: 1px solid white;
  padding: 10px;

}
</style>

</head>
<div class="container">

   {% if registered %}
                <h1>Thank you for registering!</h1>
                 <button onclick="window.location.href='{% url 'findtution:index' %}'" class="button button2">Go Back To Home Page</button> {% else %}
        <br>

             {% load crispy_forms_tags %}

            <button onclick="window.location.href='{% url 'findtution:index' %}'" class="button button2">Go Back To Home Page</button>
            <div id="graph-card">
                <h3 class="text-center">Dance Student Registration  Form</h3>
       <form  class="form-horizontal" role="form" enctype="multipart/form-data" method="POST">

                        {% csrf_token %} {% load crispy_forms_tags %}
                        <div class="row">
                         <div class="form-group col-md-6 mb-0">
                          {{ user_form.username|as_crispy_field }}
                         </div>
                         <div class="form-group col-md-6 mb-0">
                          {{ user_form.password|as_crispy_field }}
                         </div>
                         </div>
                         <div class="row">
                         <div class="form-group col-md-6 mb-0">
                          {{ profile_form3.email|as_crispy_field }}
                         </div>
                         <div class="form-group col-md-6 mb-0">
                          {{ profile_form3.city|as_crispy_field }}
                         </div>
                         </div>
                         
                     <div class="row">
                      
                         <div class="form-group col-md-6 mb-0">
                          {{ profile_form3.Danceform_You_want_to_learn|as_crispy_field }}
                         </div>
                         <div class="form-group col-md-6 mb-0">
                          {{ profile_form3.Preferred_time|as_crispy_field }}
                         </div>
                     </div>
                        <input class="btn btn-success btn-block" style="background: #3d6bce;" type="submit" name="" value="Register">
                    </form>
                     {% endif %}
     </div>
       <br>


    </div>

{% endblock %}

dappx/templates/dappx/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Findatution</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>

<body style="background:url({% static 'images/88.jpg'%}) no-repeat center center fixed;
-webkit-background-size: cover;
-moz-background-size: cover;
-o-background-size: cover;
background-size: cover;" ">

    <div class="container ">
        {% block body_block %} {% endblock %}
    </div>
</body>

</html>

dappx/templates/dappx/index.html
{% extends "dappx/base.html" %} {% load staticfiles %} {% block body_block %}
<style>
    .button {
        background-color: #4CAF50;
        /* Green */
        border: none;
        color: white;
        padding: 16px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        -webkit-transition-duration: 0.4s;
        /* Safari */
        transition-duration: 0.4s;
        cursor: pointer;
    }
    
    .button5 {
        background-color: white;
        color: black;
        border: 2px solid #555555;
    }
    
    .button5:hover {
        background-color: #555555;
        color: white;
    }
</style>
<div class="container">
    <div class="jumbotron">
        <h1>Welcome to Find A Tution !</h1>



        {# Some logic on what to display for last item#} {% if user.is_authenticated %}
        <button onclick="window.location.href='{% url 'logout' %}'" class="button button5">Logout</button> {% else %}
        <button onclick="window.location.href='{% url 'dappx:user_login' %}'" class="button button5">Login</button> {% endif %} {% if user.is_authenticated %}
        <h2>Hello {{ user.username }} Your data is sucessfully saved in our database , we will contact you in next 24 hours via E-mail. Thanks for Registration</h2>
        {% else %}
        <h2>Register if you'd like to</h2>
        <button onclick="window.location.href='{% url 'dappx:signup' %}'" class="button button5">For Registration</button>
        <button onclick="window.location.href='{% url 'findtution:index' %}'" class="button button5">Go Back To Home Page</button> {% endif %}
    </div>
</div>

{% endblock %}

dappx/templates/dappx/login.html
{% load static %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
   <!--Made with love by Mutiullah Samim -->

    <!--Bootsrap 4 CDN-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!--Fontawesome CDN-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    <!--Custom styles-->
    <link rel="stylesheet" type="text/css" href="styles.css">
    <style>


@import url('https://fonts.googleapis.com/css?family=Numans');

html,body{
background-image:url({% static 'images/1.jpeg'%});
background-size: cover;
background-repeat: no-repeat;
height: 100%;
font-family: 'Numans', sans-serif;
}

.container{
height: 100%;
align-content: center;
}

.card{
height: 370px;
margin-top: auto;
margin-bottom: auto;
width: 400px;
background-color: rgba(0,0,0,0.5) !important;
}

.social_icon span{
font-size: 60px;
margin-left: 10px;
color: #FFC312;
}

.social_icon span:hover{
color: white;
cursor: pointer;
}

.card-header h3{
color: white;
}

.social_icon{
position: absolute;
right: 20px;
top: -45px;
}

.input-group-prepend span{
width: 50px;
background-color: #FFC312;
color: black;
border:0 !important;
}

input:focus{
outline: 0 0 0 0  !important;
box-shadow: 0 0 0 0 !important;

}

.remember{
color: white;
}

.remember input
{
width: 20px;
height: 20px;
margin-left: 15px;
margin-right: 5px;
}

.login_btn{
color: black;
background-color: #FFC312;
width: 100px;
}

.login_btn:hover{
color: black;
background-color: white;
}

.links{
color: white;
}

.links a{
margin-left: 4px;
}
    </style>

</head>

<body>
<div class="container">
    <div class="d-flex justify-content-center h-100">
        <div class="card">
            <div class="card-header">
                <h3>Sign In</h3>

            </div>
            <div class="card-body">
               <form method="post" action="{% url 'dappx:user_login' %}">
               {% csrf_token %}
                <div class="input-group form-group">
               <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                <input type="text" name="username" placeholder="Username" class="form-control">
                </div>
                <div class="input-group form-group">
                 <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                <input type="password" name="password" placeholder="Password" class="form-control">
                </div>

                <input  class="btn float-right login_btn" type="submit" name="" value="Login">

            </form>



            </div>
            <div class="card-footer">
                <div class="d-flex justify-content-center links">
                    Don't have an account?<a href="/index">Sign Up</a>
                </div>
                <div class="d-flex justify-content-center">
                    <a href="{% url 'findtution:index' %}">Go Back To Homepage</a>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

dappx/templates/dappx/signup.html
{% extends "dappx/base.html" %} {% load staticfiles %} {% block body_block %}
<style>
        .button {
        background-color: #4CAF50;
        /* Green */
        border: none;
        color: white;
        padding: 16px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        -webkit-transition-duration: 0.4s;
        /* Safari */
        transition-duration: 0.4s;
        cursor: pointer;
    }

    .button1 {
        background-color: white;
        color: black;
        border: 2px solid #4CAF50;
    }

    .button1:hover {
        background-color: #4CAF50;
        color: white;
    }

    .button2 {
        background-color: white;
        color: black;
        border: 2px solid #008CBA;
    }

    .button2:hover {
        background-color: #008CBA;
        color: white;
    }

    .button3 {
        background-color: white;
        color: black;
        border: 2px solid #f44336;
    }

    .button3:hover {
        background-color: #f44336;
        color: white;
    }

    .button4 {
        background-color: white;
        color: black;
        border: 2px solid #e7e7e7;
    }

    .button4:hover {
        background-color: #e7e7e7;
    }

    .button5 {
        background-color: white;
        color: black;
        border: 2px solid #555555;
    }

    .button5:hover {
        background-color: #555555;
        color: white;
    }

    .button6 {
        background-color: white;
        color: black;
        border: 2px solid purple;
    }

    .button6:hover {
        background-color: purple;
        color: white;
    }

    .jumbotron {
        padding-top: 30px;
        padding-bottom: 30px;
        margin-bottom: 30px;
        color: inherit;
        background-color: transparent;
</style>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link href="https://fonts.googleapis.com/css?family=Work+Sans:100,200,300,400,500,600,700,800,900" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Fredericka+the+Great" rel="stylesheet">

<link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/animate.css' %}">

<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

<link rel="stylesheet" href="{% static 'css/aos.css' %}">

<link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">

<link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<div class="">
    <div class="jumbotron">
        <h1>Welcome to Find A Tution !</h1>

        <button onclick="window.location.href='{% url 'dappx:register' %}'" class="button button2">I am a Student</button>
        <button onclick="window.location.href='{% url 'dappx:register1' %}'" class="button button3">I am a Home Tutor</button>
        <button onclick="window.location.href='{% url 'dappx:register2' %}'" class="button button1">I am from Tution POint</button>
        <button onclick="window.location.href='{% url 'findtution:index' %}'" class="button button6">Go Back To Home Page</button> {# Some logic on what to display for last item#} {% if user.is_authenticated %}
        <button onclick="window.location.href='{% url 'logout' %}'" class="button button5">Logout</button> {% else %}
        <button onclick="window.location.href='{% url 'dappx:user_login' %}'" class="button button5">Login</button> {% endif %} {% if user.is_authenticated %}
        <h2>Hello {{ user.username }} Your data is sucessfully saved in our database , we will contact you in next 24 hours via E-mail. Thanks for Registration</h2>
        {% else %}
        <h2>Register or Login if you'd like to</h2>



        {% endif %}
    </div>
</div>

{% endblock %}